#!/usr/bin/env node

const {execSync} = require('child_process');
const fs = require('fs');

// Check the first argument passed to the script
const command = process.argv[2];

if (command === 'install') {
    console.log('Installing dependencies...');

    // First, install npm dependencies
    execSync('npm install', {stdio: 'inherit'});

    // Install TypeScript for compiling
    execSync('npm install typescript --save-dev', {stdio: 'inherit'});

    // Install jest for testing
    execSync('npm install jest --save-dev', {stdio: 'inherit'});

    // Compile the TypeScript files
    execSync('npm run build', {stdio: 'inherit'});

    // Indicate that installation is done
    fs.writeFileSync('.installed', 'Installation complete');

    console.log('Installation completed.');

} else if (fs.existsSync('./dist/index.js')) {
    require('../../../dist/index.js');  // Load CLI
} else {
    console.error("The project hasn't been built yet. Please run './run install' first.");
    process.exit(1);
}